#### Preamble ####
# Purpose: Tests the simulated Poll-of-Polls data for the US President Elections 2024 
# generated by the file 00-simulate_data.R
# Author: Aamishi Avarsekar, Divya Gupta, Gaurav Thind
# Date: 4th November 2024
# Contact: aamishi.avarsekar@mail.utoronto.ca
# License: MIT

# the following code was created by ChatGPT 4.0

# Load necessary libraries
library(dplyr)
library(testthat)

# Define the simulated data-generating function
generate_poll_data <- function(n = 500) {
  tibble(
    pollster_id = sample(1:50, n, replace = TRUE),
    pollster_name = paste("Pollster", pollster_id),
    level = sample(c("national", "state"), n, replace = TRUE, prob = c(0.3, 0.7)),
    state = ifelse(level == "state", 
                   sample(state.name, n, replace = TRUE), 
                   NA_character_),
    leaning = sample(c("Democratic", "Republican", "Swing"), n, replace = TRUE),
    duration = sample(3:15, n, replace = TRUE),
    poll_quality = round(runif(n, 1, 5), 1),
    predicted_part = sample(c("Democratic", "Republican"), n, replace = TRUE),
    predicted_candidate = ifelse(predicted_part == "Democratic",
                                 sample(c("Harris", "Biden"), n, replace = TRUE),
                                 sample(c("Trump", "Hailey"), n, replace = TRUE))
  )
}

# Generate test data
poll_data <- generate_poll_data()

# Begin tests
test_that("pollster_id is within the expected range and is integer", {
  expect_true(all(poll_data$pollster_id >= 1 & poll_data$pollster_id <= 50))
  expect_type(poll_data$pollster_id, "integer")
})

test_that("pollster_name corresponds to pollster_id", {
  expect_true(all(grepl("Pollster", poll_data$pollster_name)))
  expect_equal(poll_data$pollster_name, paste("Pollster", poll_data$pollster_id))
})

test_that("level is either national or state", {
  expect_true(all(poll_data$level %in% c("national", "state")))
  expect_equal(sum(poll_data$level == "national") / nrow(poll_data) >= 0.2, TRUE) # at least some are national
})

test_that("state is either a valid U.S. state name or NA for national level polls", {
  valid_states <- c(state.name, NA)
  expect_true(all(poll_data$state %in% valid_states))
  expect_true(all(is.na(poll_data$state[poll_data$level == "national"])))
})

test_that("leaning contains only expected values", {
  expect_true(all(poll_data$leaning %in% c("Democratic", "Republican", "Swing")))
  expect_equal(sum(poll_data$leaning == "Swing") > 0, TRUE) # some should be swing
})

test_that("duration is within the expected range", {
  expect_true(all(poll_data$duration >= 3 & poll_data$duration <= 15))
  expect_type(poll_data$duration, "integer")
})

test_that("poll_quality is between 1 and 5 and has numeric type", {
  expect_true(all(poll_data$poll_quality >= 1 & poll_data$poll_quality <= 5))
  expect_type(poll_data$poll_quality, "double")
})

test_that("predicted_part contains only Democratic or Republican", {
  expect_true(all(poll_data$predicted_part %in% c("Democratic", "Republican")))
  expect_equal(sum(poll_data$predicted_part == "Democratic") > 0, TRUE) # some are Democratic
  expect_equal(sum(poll_data$predicted_part == "Republican") > 0, TRUE) # some are Republican
})

test_that("predicted_candidate corresponds to the predicted_part", {
  dem_candidates <- c("Harris", "Biden")
  rep_candidates <- c("Trump", "Hailey")
  expect_true(all(poll_data$predicted_candidate[poll_data$predicted_part == "Democratic"] %in% dem_candidates))
  expect_true(all(poll_data$predicted_candidate[poll_data$predicted_part == "Republican"] %in% rep_candidates))
})